### ISSUE TITLE
Missing step in node setup?

### ISSUE THREAD

**Issue by phoniks** [uport-project/veramo-website#144]
It seems to me that there might be a step missing in the tutorial on bootstrapping node.   In between the List Identifiers and Create Identifiers steps it seems like there's a bit of config that needs to happen.  The CLI itself suggests running `npx @veramo/cli config create-secret-key`

Which I did, but I'm not sure where to check that the agent knows where to look for my key.  Can anyone provide some guidance?  I'll be happy to make a PR updating the docs as well, once I figure it out.

**Comment by phoniks** [comment]
whoops, sorted it out.  Turns out the error I was reading was just an output of the value that was being read into Veramo, so I replaced that line with the key and everything worked as expected.  I'll make a PR to try to capture this next week if that's useful but feel free to close the issue.

**Comment by mirceanis** [comment]
Thanks for the feedback!
A PR is welcome as any clarification is helpful :)
