### ISSUE TITLE
Basic Use Cases using core plugings

### ISSUE THREAD

**Issue by pvanroos** [uport-project/veramo-website#29]
The documentation on the website is a very good introduction and great start to the Veramo project.  It helped establish the basis for my understanding of the DID domain.  

Are there any examples of using all the core plugins to achieve some larger use cases--specifically something that shows very common workflows?

I could use some help setting up the DIDs and then executing a SelectiveDisclosureRequest using some verifiable creds and data.  I understand cryptography and key management but I'm trying to get my head around the basic use cases.  Specific examples showing this step by step would be very helpful.  Once I understand how to interact with the Agent to do these core things, I can then elaborate on my more advanced needs which may require a custom plugin.

Thanks guys!

**Comment by jasonhealy** [comment]
Thanks for the feedback. Agreed we need to have more full flow type tutorials. Each guide is actually written as the basic first step of many for these flows. In Q1 we intend on adding the next steps to many of these guides with the intent of pulling them all together e.g. the mobile RN tutorials will eventually culminate in some interaction with the cloud agent and vice versa and perhaps an official Veramo VC issuer will also be part of the flows.

**Comment by pvanroos** [comment]
Thanks Jason.  I'm playing with the tools now and building out my solution.  I have the Agent deployed on Heroku and I've been able to run the CLI on a Linux node.  I am not blocked so no worries.  I'll provide more feedback as I progress.
