### ISSUE TITLE
react-native errors in metro: "TextEncoder" and "AppRegistry is not a registered callable module"

### ISSUE THREAD

**Issue by trentlarson** [uport-project/veramo-website#33]
I get the following errors in the Metro packager window when I run the react-native instructions for iOS on a Mac.  Note that I'm following the `docs/react-native-guide-update` branch in order to get the fixes from https://github.com/uport-project/veramo-website/blob/docs/react-native-guide-update/docs/guides/react_native.md

```
[Fri Jan 01 2021 13:06:03.685]  ERROR    ReferenceError: Can't find variable: TextEncoder
[Fri Jan 01 2021 13:06:03.686]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Fri Jan 01 2021 13:06:04.690]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

The app runs fine after the "Install Dependencies" and "Bootstrap Veramo" steps.  (I added a line `const infuraProjectId = '...'` before the `export const agent` line in `setup.ts`)

I get these errors whether I run `npx react-native run-ios` or `xed -b ios`

The last line of my original terminal says `success Successfully launched the app on the simulator`.  The simulator flashes the word "Veramo" but then it goes away and just shows a blank page.

I see no references to TextEncoder anywhere in the source.  The only references to AppRegistry are in `index.js`

There are two parts of the instructions that I may not have done right:

- It says to "clean the project" at the end of the "Native" section, but I don't know how to do that.  There is no `yarn clean`.  I tried installing and running the `react-native-clean-project` but that didn't help.
- It says to "rebuild the app" after editing `App.tsx`, but I don't know how to do that.  I have CTRL-C in the Metro packager to quit and then run `npx react-native run-ios` (multiple times) but that didn't help.

It also showed the following warning in the Metro window but I assume it's irrelevant.
```
[Fri Jan 01 2021 13:06:03.684]  WARN     Require cycle: node_modules/z-schema/src/SchemaCache.js -> node_modules/z-schema/src/SchemaCompilation.js -> node_modules/z-schema/src/SchemaCache.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

**Comment by jasonhealy** [comment]
It looks like a bug was introduced during the renaming refactoring. We will look into this asap.

**Comment by trentlarson** [comment]
Thank you for the update!

I've been using uPort tools for a couple years now, and although it has worked for my private project I'll be honest that the lack of responsiveness earlier on in the project has been concerning and given me pause when I consider going wider.  There have been multiple forums (eg. chat.uport.me, uport.zendesk.com, and Discord I think) but it seemed difficult to get responses on them.  Even just a note like you wrote is helpful.  I'm encouraged by some of the responsiveness here in the PRs, I hope that you're all able to spend time engaging with the community, and I look forward to making the new code approaches work.  Cheers!

**Comment by jasonhealy** [comment]
@trentlarson Thanks for the feedback! We will definitely take this on-board.

Regarding the issue. I have updated the [react native docs](https://veramo.io/docs/guides/react_native) with the solution. 

To summarise the issue ~ We depend on a library called `did-jwt`.  Recently this was upgraded to use `uint8arrays` which depends on `web-encoding`. This lib depends the `TextEncoder API`.  Adding a polyfill for the TextEncoder API fixes this. See updated docs on how to add it.

Separately the `shim.js` that gets created by `rn-nodeify` needs to be imported to your app.


Let us know if this works for you?

**Comment by trentlarson** [comment]
I cloned the repo again and followed the latest instructions on veramo.io and I still get the same errors.

**Comment by gbugyis** [comment]
@trentlarson You may need to run `yarn start —reset-cache` to reset Metro’s cache. You’re still seeing the same original error? I have a PR with a couple tiny edits to the RN guide, but they’re for after you get past the ones you’re seeing.

**Comment by trentlarson** [comment]
OK, maybe progress... I get different failures now.

Here are my steps.  But: note that there is no index.ts so that part is different.

- `rm -rf veramoRN`
- `npx react-native init veramoRN --template react-native-template-typescript`
- `cd "/Users/tlarson/dev/home/veramoRN" && npx react-native run-ios`
- successfully see Metro in another window & the app running
- quit simulator, quit Metro, then restart Metro with the next line:
- `yarn start --reset-cache`
- make all other ["Native" changes](https://veramo.io/docs/guides/react_native#native), with shim & text-encoding in index.js instead (due to lack of index.ts file)
- `npx react-native run-ios`

#### Error 1

So that's where it throws up, before I get to ["Veramo" changes](https://veramo.io/docs/guides/react_native#veramo).

```
error: index.js: Cannot find module '/Users/tlarson/dev/home/veramoRN/node_modules/@react-native-community/cli/node_modules/metro-react-native-babel-transformer/src/index.js'
Require stack:
- /Users/tlarson/dev/home/veramoRN/node_modules/metro/src/JSTransformer/worker.js
- /Users/tlarson/dev/home/veramoRN/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/tlarson/dev/home/veramoRN/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js
```

#### Error 2

One guess is that all the index.js changes need to be in an index.ts file instead, but if I try creating that file then I get this error:

```
[Sun Jan 17 2021 08:20:20.822]  BUNDLE  ./index.ts

error: Error: Unable to resolve module `events` from `node_modules/stream-browserify/index.js`: events could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/tlarson/dev/home/veramoRN/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/tlarson/dev/home/veramoRN/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/tlarson/dev/home/veramoRN/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/tlarson/dev/home/veramoRN/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/tlarson/dev/home/veramoRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/tlarson/dev/home/veramoRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/tlarson/dev/home/veramoRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tlarson/dev/home/veramoRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

I've tried a few versions of index.ts, where I put all the contents of index.js into it or I just put parts in there and parts in index.js, to no avail.

Note that the instructions say to insert the following into index.ts:

```
{
  import './shim'
  import '@zxing/text-encoding'

  ...
}
```

That looks wrong, with the curly braces at the beginning and at the end, so I left those out as I did my experiments.  I don't have the time right now to try that particular piece of code... I will try that if you like, but I'd appreciate it if you'd send me the index.js and the index.ts that you have for reference.

**Comment by gbugyis** [comment]
@trentlarson I pushed the result of my run through to [this repo](https://github.com/gbugyis/veramo-react-native-guide).  I also encountered Error 2 (thought it was just my local setup). Running `yarn add events` took care of it.

**Comment by trentlarson** [comment]
Woo hoo!  I have a working app!  I have a working app!

The rest of the instructions worked great.  This is awesome... I will start working in this instead of the old daf-mobile.  Thank you, thank you.

**Comment by trentlarson** [comment]
So... last thing would be to make some of those changes in the veramo-website repo (index.ts vs index.js, index.ts imports, and `yarn add events`).  Unless you're already working on that, I'll make a PR for them.

**Comment by jasonhealy** [comment]
Great! No need to have `events` installed separately as it should be installed with [@veramo/core](https://www.npmjs.com/package/@veramo/core) - might have been some sort of rn caching issue that it didn't find it.

**Comment by trentlarson** [comment]
I tried again from scratch and still got that problem with `events`.  I ran `yarn global list` and I don't see anything related to those packages, so I can't figure out why it wouldn't be included.  Very odd.
