### ISSUE TITLE
Update React Native tutorial

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/veramo-website#83]
https://veramo.io/docs/react_native_tutorials/react_native_setup_identifers

This tutorial still references `react-native-sodium` and `@veramo/kms-local-react-native`

**Comment by mirceanis** [comment]
since version 2.0.0 `@veramo/kms-local-react-native` is no more.
On react-native, please use `@veramo/kms-local` instead, along with with `@ethersproject/shims`
